# Generated by Django 4.0.3 on 2022-04-02 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_alter_solar_energy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar_energy',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
