# Generated by Django 4.0.3 on 2022-04-27 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_alter_solar_energy_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar_energy',
            name='transactionID',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='solar_energy',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
